### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by zhuzhongzhi-50** [Zhuzzq/EdgeFed-MARL-MEC#2]
# Error Message：
epoch2073
Traceback (most recent call last):
File "e: /wuzhu/Documents/Visual Studio Code/EdgeFed-MARL-MEC-master/AC_run.py", line 88, in <module>
AC. train(MAX_EPOCH, MAX_EP_STEPS, up_freq=up_freq, render=True, render_freq=render_freq)
File "e: \wuzhu\Documents\Visual Studio Code\EdgeFed-MARL-MEC-master\AC_agent.py", line 379, in train
cur_reward = self.actor_act (epoch)
File "e: \wuzhu\Documents \Visual studio Code\EdgeFed-MARL-MEC-master \AC_agent.py", line 243, in actor_act
move _ori = circle_argmax(move _dist, self.env.move_r)
File "e: \wuzhu\Documents \isual Studio Code\EdgeFed-MARL-MEC-master\AC_agent.py", line 156, in circle_argmax
return max_pos[np.argmin(pos_dist)]
File "< array functioninternals>", line 6, in argmin
"F: \anaconda3\envs\test\lib\site-packages \numpy\core\fromnumeric.py", line 1269, in argmin
return _wrapfunc(a,'argmin', axis=axis, out=out)
File "F: \anaconda3\envs\test\lib\site-packages\numpy\core\fromnumeric.py" line 58, in _wrapfunc
return bound (*args,**kwds)
ValueError: attempt to get argmin of an empty sequence

`
# Code Section：AC_agent.py
def circle_argmax(move_dist, move_r):
    max_pos = np.argwhere(tf.squeeze(move_dist, axis=-1) == np.max(move_dist))
    # print(tf.squeeze(move_dist, axis=-1))
    pos_dist = np.linalg.norm(max_pos - np.array([move_r, move_r]), axis=1)
    # print(max_pos)
    return max_pos[np.argmin(pos_dist)]
`

# Describe：
Hello, when I was training your code, after the 2073rd round of training, I reported the above error. Have you encountered a similar error message? How was it resolved?

**Comment by Zhuzzq** [comment]
I didn't get that error before. As described, it might be helpful to check the input/output of the model or the NaN errors.

**Comment by zhuzhongzhi-50** [comment]
OK, I'll try. Thank you for your reply
